language: python
python: 2.7

env:
    - TOX_ENV=docs
    - TOX_ENV=lint
    - TOX_ENV=py26
    - TOX_ENV=coverage

install:
    - pip install tox python-coveralls

script:
    - tox -e $TOX_ENV

after_success:
    coveralls --data_file=/tmp/.tox/coverage/tmp/.coverage
