# Copyright (C) 2013 Ivan Kravets <me@ikravets.com>
# See LICENSE for details.
---
logger:
    level: INFO  # DEBUG, INFO, WARN, ERROR, FATAL

# System services.
# The each service should have:
# - key: the unique name
# - enabled: the flag can be set to "Yes" or "No"
# - options: the list with predefined options
services: []
...
